---
- name: setup user {{ user_item.login }}
  uri:
    url: "http://localhost:8080/geoserver/rest/security/usergroup/service/{{ user_item.service }}/users/"
    method: POST
    user: admin
    password: "{{ geoserver_admin_password }}"
    force_basic_auth: true
    body_format: json
    body:
      user:
        userName: "{{ user_item.login }}"
        password: "{{ user_item.password }}"
        enabled: "{{ user_item.enabled | default('true') }}"
  register: create_user_response
  failed_when: create_user_response.status not in [200, 201, 404]
  no_log: True

- name: setup user {{ user_item.login }} (update password)
  uri:
    url: "http://localhost:8080/geoserver/rest/security/usergroup/service/{{ user_item.service }}/user/{{ user_item.login }}/"
    method: POST
    user: admin
    password: "{{ geoserver_admin_password }}"
    force_basic_auth: true
    body_format: json
    body:
      user:
        password: "{{ user_item.password }}"
        enabled: "{{ user_item.enabled | default('true') }}"
  register: create_user_response
  when: create_user_response.status in [404]
  failed_when: create_user_response.status not in [200]
  no_log: True
