---
- block:
    - name: Download and unpack the Geoserver css extension
      unarchive:
        copy: no
        src: "{{ geoserver_css_url }}"
        dest: "{{ geoserver_instance_path }}/{{ geoserver_version }}/webapps/geoserver/WEB-INF/lib/"
        owner: "{{ geoserver_user }}"
        group: "{{ geoserver_user_group }}"
      notify: Restart geoserver services
  when: geoserver_css_install
  tags: [ 'geoserver', 'css' ]
