---
- name: facts
  import_tasks: facts.yml

- name: dependencies
  import_tasks: dependencies.yml

- name: preparation
  import_tasks: preparation.yml

- import_tasks: geoserver.yml

- import_tasks: geoserver-users.yml  

- import_tasks: enable-cors.yaml
  when: geoserver_enable_cors is defined and geoserver_enable_cors | bool

- import_tasks: geoserver-spatialite.yml
  when: geoserver_spatial_install

- import_tasks: geoserver-vectortiles.yml
  when: geoserver_vectortiles_install

- import_tasks: geoserver-css.yml
  when: geoserver_css_install

- import_tasks: marlin-renderer.yml
  when: geoserver_marlin_renderer

- name: geoserver service
  import_tasks: geoserver-service.yml